In [3]:
import numpy as np

# Création d'une matrice 9x9 remplie de 1
matrix = np.ones((9, 9), dtype=np.int8)
print(matrix, "\n")
# Remplissage des zéros à l'intérieur
matrix[1:-1, 1:-1] = 0  # On modifie tout sauf les bords

# Ajout des 1 aux bonnes positions
matrix[2:-2:2, 2:-2:2] = 1  # Positionne les 1 en diagonale interne
print(matrix, "\n")
# Création des tableaux
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8).reshape(-1, 1)  # (5,1)
array_2 = np.array([1, 2, 3], dtype=np.int8).reshape(1, -1)  # (1,3)

# Broadcasting : Multiplication des deux tableaux
result = array_1 * array_2

print(result, "\n")



[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] 

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] 

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]] 

