In [3]:
import numpy as np

# Générateur de nombres aléatoires avec seed
generator = np.random.default_rng(123)

# Création de la matrice des notes (10 étudiants, 2 examens)
grades = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))

# Remplacement de certaines notes du premier examen par NaN
grades[[1, 2, 5, 7], 0] = np.nan  # Les indices 1, 2, 5, 7 du premier examen deviennent NaN

# Affichage des notes initiales
print("Notes initiales :\n", grades)


# Création de la 3ème colonne avec np.where
third_column = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])

# Ajout de la colonne au tableau d'origine
grades = np.column_stack((grades, third_column))

# Affichage du résultat
print("\nTableau final avec la 3ème colonne :\n", grades)


Notes initiales :
 [[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]
[ 7. nan nan  9.  8. nan  8. nan  9.  8.]
[1. 2. 8. 3. 9. 2. 2. 6. 2. 5.]

Tableau final avec la 3ème colonne :
 [[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]
